server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_accounts?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Qwerty123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            directory:
              root: ${user.home}/indexes
  messages:
    basename: messages
    encoding: UTF-8
logging:
  level:
    org:
      hibernate:
        search: DEBUG
    